language: android
jdk: oraclejdk8
sudo: required
env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=29.0.1
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-$ANDROID_API_LEVEL
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod a+x gradlew
  - yes | sdkmanager "platforms;android-28"
# before_script:
#  - mkdir -p "$ANDROID_HOME/licenses"
#  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
script:
  - ./gradlew build check --stacktrace